global using FluentResults;
global using MainCore.Commands;
global using MainCore.Commands.Navigate;
global using MainCore.Commands.Update;
global using MainCore.Common.Enums;
global using MainCore.Common.Errors;
global using MainCore.Entities;
global using MainCore.Infrasturecture.AutoRegisterDi;
global using MainCore.Notification.Message;
global using MainCore.Parsers;
global using MainCore.Repositories;
global using MainCore.Services;
global using MediatR;
global using OpenQA.Selenium;
global using Unit = System.Reactive.Unit;