name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: windows-latest
    env:
        DOTNET_INSTALL_DIR: "D:/tools/dotnet"
        DOTNET_ROOT: "D:/tools/dotnet"
        NUGET_PACKAGES: "D:/.nuget/packages"
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
        
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: dotnet restore --locked-mode
        
      - name: Test architecture
        run: dotnet test -c Debug --filter Mode=Debug
        
      - name: Test others
        run: dotnet test -c Release --filter Mode!=Debug
        
  Version:
    runs-on: ubuntu-latest
    needs: Test
    permissions:
        contents: write
    outputs:
      version: ${{ steps.semvers.outputs.patch }}
    steps:
      - name: Checkout 
        uses: actions/checkout@v4.1.5
        with:
          fetch-depth: 0 
      
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0  
        with:
          fallback: 1.0.0
      
      - name: Get next version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1.2.1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          
      - name: Create tag
        uses: rickstaa/action-create-tag@v1.7.2
        with:
          tag: ${{ steps.semvers.outputs.patch }}
          tag_exists_error: false
          message: TBS-${{ steps.semvers.outputs.patch }}
  Build:
    runs-on: windows-latest
    needs: Version
    env:
        DOTNET_INSTALL_DIR: "D:/tools/dotnet"
        DOTNET_ROOT: "D:/tools/dotnet"
        NUGET_PACKAGES: "D:/.nuget/packages"
    
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
        
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Install dependencies
        run: dotnet restore --locked-mode
      
      - name: Publish
        run: dotnet publish WPFUI -c Release --no-restore --self-contained -p:PublishSingleFile=true -p:AssemblyVersion=${{needs.version.outputs.version}}
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: TBS-${{needs.version.outputs.version}}
          path: WPFUI\bin\Release\net8.0-windows10.0.19041.0\win-x64\publish\
          if-no-files-found: error
  Comment:
    needs: [Build, Version]
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2.5.0
        with:
          message: |
            Version of this build is ${{needs.version.outputs.version}}
            Check download link [here](https://nightly.link/vinaghost/TravianBotSharp/actions/runs/${{ github.run_id }})
